## Librerie

In [2]:
import pandas as pd

## Caricamento

In [3]:
## Da file
studenti = pd.read_csv("studenti.csv")
studenti_nuovi = pd.read_pickle("studenti_nuovi.pkl")
## Inizializzazione
nuovo = {
    "Nome" : ["Alessandro"],
    "Cognome" : ["Ciao"],
    "Codice" : [100],
    "Classe" : ["1AIN"]
}
pd.DataFrame(nuovo)

         Nome Cognome  Codice Classe
0  Alessandro    Ciao     100   1AIN

## Analizziamo

In [4]:
# studenti
## Modifico la troncatura
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 500)
studenti
### Visionamento generale
## Dimensioni
# studenti.shape
## Inizio - fine
# studenti.head(2)
# studenti.tail(2)

            Nome      Cognome   Codice Classe                    Voti  Promosso  Comportamento
0           Inga       Adolfo  11981.0   1AIN         [3 8 6 9 3 7 7]       1.0            8.0
1           Leon        Bardo  11982.0   1AIN         [8 6 7 6 3 8 3]       0.0           10.0
2           Orso   Elisabetta  11983.0   1AIN         [8 4 8 7 9 5 7]       1.0            9.0
3          Megan   Guendalina  11984.0   1AIN  [ 4 10  5  7 10  7  4]       1.0           10.0
4            Pio      Eugenio  11985.0   1AIN         [5 9 6 4 7 9 6]       1.0            9.0
5       Raimonda     Giuliana  11986.0   1AIN         [6 9 7 9 5 9 5]       1.0            9.0
6         Tullia         Fara  11987.0   1AIN         [5 6 4 7 3 3 3]       0.0           10.0
7         Silvia     Gardenia  11988.0   1BEN  [ 9  9  8  6  3 10  4]       1.0            8.0
8        Simeone      Assunta  11989.0   1BEN  [ 9  6  5  8  4 10  6]       1.0            9.0
9           Nara     Graziano  11990.0   1BEN  [10  6  9  7  7  3 10]       1.0            9.0
10           Ada      Doriana  11991.0   1BEN  [10  5  8  8  6  4  8]       1.0           10.0
11         Maria       Lilith  11992.0   1BEN  [ 6  9 10  4  9  4  7]       1.0            8.0
12         Alida        Altea  11993.0   1BEN  [ 8  8  6  3  3 10  3]       0.0            8.0
13       Jessica      Ignazio  11994.0   1BEN  [ 8  6 10 10  7  7  9]       1.0           10.0
14       Leonida        Aime√®  11995.0   1BEN  [ 8 10  9  7  8  8  5]       1.0            7.0
15       Ignazio        Ermes  11996.0   1BEN  [ 9 10  9  8  5  9  4]       1.0           10.0
16           Tia       Egidio  11997.0   1BEN  [ 7  4 10  8  3  4  6]       1.0           10.0
17      Lancelot      Edgardo  11998.0   1CEN         [4 4 4 5 6 4 5]       0.0            7.0
18       Satinka        Bruna  11999.0   1CEN  [ 8  8  3  5  4  9 10]       1.0            9.0
19        Altair         Jael  12000.0   1CEN  [ 5  6 10  6  3  4 10]       1.0           10.0
20     Anastasia          Ebe  12001.0   1CEN  [10  8  6  9  5  8  7]       1.0           10.0
21        Cedric        Bjorn  12002.0   1CEN  [ 5  7  4  7 10  3  6]       1.0            7.0
22        Cesara         Vida  12003.0   1CEN         [7 5 3 5 8 9 3]       0.0            8.0
23       Leonida      Madonna  12004.0   1CEN         [9 9 6 6 9 8 7]       1.0            9.0
24           Era     Filomena  12005.0   1CEN  [ 3  6  9  5  7  8 10]       1.0            8.0
25          Ford       Rowena  12006.0   1DIN         [4 7 8 6 9 4 9]       1.0           10.0
26        Enrica      Letizia  12007.0   1DIN  [ 9  9  6  9 10  4  5]       1.0            9.0
27          Dina        Medea  12008.0   1DIN  [ 3  4  3 10  8  8  8]       1.0           10.0
28        Evania       Melvin  12009.0   1DIN  [ 5  6  9  9 10  3  6]       1.0            9.0
29       Malvina      Marilyn  12010.0   1DIN         [4 6 6 9 8 3 7]       1.0            7.0
30       Gustavo      Elettra  12011.0   1DIN         [6 9 7 4 4 9 6]       1.0            8.0
31        Silvia        Maude  12012.0   1DIN         [7 4 5 8 5 3 9]       0.0            9.0
32        Urania      Primula  12013.0   1EEN         [9 4 3 8 7 3 9]       1.0            8.0
33      Fiorella       Rohana  12014.0   1EEN  [ 6 10  3  7  3  5  7]       0.0            8.0
34      Manfredo         Ciro  12015.0   1EEN         [8 8 6 9 8 7 7]       1.0            8.0
35       Romilda    Salvatore  12016.0   1EEN         [4 9 4 8 7 8 5]       1.0            7.0
36         Melia    Polissena  12017.0   1EEN  [10  9  9  7  8  5  4]       1.0            8.0
37       Celesta      Mildred  12018.0   1EEN  [10  9  6  9  3  3  6]       1.0           10.0
38        Mirina        Xenia  12019.0   1EEN  [ 4  5 10  5  3  8  7]       1.0            8.0
39          Edda       Xantha  12020.0   1EEN         [9 3 9 4 9 3 9]       1.0            8.0
40          Elia     Emiliana  12021.0   1FEN  [ 8  8 10  9  5  5  9]       1.0            9.0
41         Zelia       Annika  12022.0   1FEN         [8 6 8 3 3 9 6]       1.0            9.0
42         Lidia     Vincenzo  12023.0   1FEN         [4 8 5 3 9 6 6]       0.0           10.0
43     Genoveffa    Aquilante  12024.0   1FEN  [ 9  5  8  5 10  7  5]       1.0           10.0
44          Ivan      Rosalia  12025.0   1FEN  [ 9  5 10  9  3  9  8]       1.0            8.0
45       Adriana      Attilio  12026.0   1FEN  [ 6  8  6  6 10  7  9]       1.0            7.0
46      Marilena   Costantino  12027.0   1FEN         [9 5 5 5 8 9 6]       1.0            8.0
47       Velania         Egle  12028.0   1FEN  [ 8  9  7 10  5  8  5]       1.0           10.0
48          Ymir         Igea  12029.0   1FEN         [5 6 7 4 4 8 4]       0.0            9.0
49      Euridice         Ford  12030.0   1GIN  [ 7  9  7 10  6  8  9]       1.0           10.0
50         Fabio      Zuleika  12031.0   1GIN         [3 4 3 5 7 7 6]       0.0            9.0
51         Milva      Ornella  12032.0   1GIN  [10  9  9  6  4  9  5]       1.0            8.0
52        Duilio     Galeazzo  12033.0   1GIN  [10  4  6 10  5  7  3]       1.0            7.0
53          Otto       Oreste  12034.0   1GIN  [ 7  7  5  9  6 10  5]       1.0            9.0
54        Leslie         Edda  12035.0   1GIN         [6 4 3 6 5 9 7]       0.0            8.0
55         Talia    Anastasia  12036.0   1GIN         [9 8 8 5 3 7 7]       1.0            9.0
56       Anselmo        Folco  12037.0   1GIN         [4 9 9 6 8 9 4]       1.0            7.0
57        Rowena         Aura  12038.0   1GIN         [6 7 8 3 6 8 3]       0.0            8.0
58     Edelweiss          Ugo  12039.0   1GIN  [10  3  6  6  5  4  6]       0.0            8.0
59      Ortensia       Romolo  12040.0   1HIN         [4 6 8 5 9 4 3]       0.0           10.0
60      Mercedes      Melania  12041.0   1HIN  [ 5  9  3  6  4 10  7]       1.0            7.0
61         Liala         Luna  12042.0   1HIN  [10  3  3  6  4  3  8]       0.0            8.0
62       Ancilla   Costantino  12043.0   1HIN         [9 5 7 4 6 4 9]       1.0            7.0
63       Cecilia      Camillo  12044.0   1HIN  [ 5  4 10 10  9  9  8]       1.0            9.0
64         Olisa          Eco  12045.0   1HIN  [ 8 10  5  4  3  8  8]       1.0            8.0
65      Beatrice       Bianca  12046.0   1HIN  [10 10  8  8  9  9  4]       1.0            9.0
66         Mario      Natalia  12047.0   1HIN  [10  7  3  8  7  3  7]       1.0            8.0
67       Rachele      Camelia  12048.0   1HIN  [ 4  9  7 10  4  8  5]       1.0            9.0
68        Werner   Margherita  12049.0   1IIN         [7 7 4 7 9 5 4]       1.0            9.0
69       Paralda         Wala  12050.0   1IIN         [9 8 8 8 3 3 7]       1.0            7.0
70      Ludovico      Tiffany  12051.0   1IIN         [4 6 6 6 6 4 7]       0.0            8.0
71         Kamar       Moanna  12052.0   1IIN  [ 5  5  7  6  9 10  7]       1.0            8.0
72        Onella      Santino  12053.0   1IIN         [9 7 5 5 9 9 8]       1.0           10.0
73      Floriano         Egle  12054.0   1IIN  [ 3  5  5  7 10  6 10]       1.0            7.0
74       Alberto        Izusa  12055.0   1IIN  [10  3  9  3  6  9  7]       1.0            8.0
75       Vittore   Sebastiano  12056.0   1IIN  [ 5 10 10  3  9 10  5]       1.0            8.0
76       Vassjli      Morgana  12057.0   1JIN         [4 7 5 7 9 3 4]       0.0            9.0
77       Dolcina     Perceval  12058.0   1JIN  [ 5  8  3  8 10  7  3]       1.0           10.0
78          Lora     Fiorenzo  12059.0   1JIN         [7 9 4 3 5 6 3]       0.0            8.0
79      Adelaide     Samantha  12060.0   1JIN  [ 8  5  7 10 10  6  7]       1.0            8.0
80      Marilena      Candida  12061.0   1JIN         [7 7 9 6 7 6 8]       1.0           10.0
81         Mario       Romolo  12062.0   1JIN  [10  9  5 10  8  4  9]       1.0           10.0
82           Sem        Drago  12063.0   1JIN         [4 8 4 8 7 3 3]       0.0            7.0
83        Thelma       Andrea  12064.0   1JIN         [5 4 3 7 6 8 4]       0.0            9.0
84        Alhena      Mafalda  12065.0   1JIN  [ 3  7 10  8  7  7 10]       1.0            7.0
85          Orio         Enki  12066.0   1JIN         [6 4 9 9 4 9 5]       1.0            8.0
86       Giacomo      Celeste  12067.0   1KEN         [8 8 6 5 3 9 7]       1.0            9.0
87    Guicciardo     Ambrogio  12068.0   1KEN         [6 9 5 5 7 4 3]       0.0            9.0
88       Bibiana      Barbara  12069.0   1KEN  [10  4  5  7 10  9  5]       1.0            7.0
89          Vito        Uriel  12070.0   1KEN  [10  4  5  9  4  6  5]       1.0           10.0
90       Ignazio         Alan  12071.0   1KEN  [ 8  6 10  3  8 10  8]       1.0           10.0
91        Donato     Ludmilla  12072.0   1KEN         [5 3 4 3 8 3 6]       0.0            9.0
92       Melania      Alfredo  12073.0   1KEN  [ 5  9  6 10  4  8  9]       1.0           10.0
93        Donata         Elfo  12074.0   1KEN         [8 6 8 6 3 3 6]       0.0           10.0
94    Sebastiano        Ivana  12075.0   2AEN  [ 3  5  5  7  5  6 10]       0.0            8.0
95         Athos      Zuleika  12076.0   2AEN         [9 9 9 9 6 7 3]       1.0            7.0
96           Nem       Moanna  12077.0   2AEN  [ 3  9  4 10  3  6  3]       0.0            7.0
97        Kendra    Ferruccio  12078.0   2AEN         [6 6 7 3 4 4 8]       0.0            8.0
98           Lia       Carina  12079.0   2AEN         [7 7 9 6 7 8 7]       1.0            8.0
99       Alfonso        Frida  12080.0   2AEN  [10  6  3  4 10  9 10]       1.0            9.0
100      Massimo        Jader  12081.0   2AEN         [4 8 9 7 3 9 4]       1.0           10.0
101     Domenica      Valeria  12082.0   2AEN  [ 6  7  7 10  8  6  3]       1.0            8.0
102      Verilla        Delia  12083.0   2AEN         [7 7 7 4 9 8 5]       1.0            7.0
103      Delfino      Gaspare  12084.0   2AEN  [ 9  5  5  4  5 10  8]       1.0           10.0
104        Edith        Alida  12085.0   2BEN         [3 7 9 8 5 9 8]       1.0            9.0
105     Giuliana     Fiorenza  12086.0   2BEN  [ 7  6  5  9  5  9 10]       1.0            9.0
106         Dino         Emma  12087.0   2BEN  [ 5 10  3  5  3  8 10]       1.0            8.0
107      Adriele        Nadia  12088.0   2BEN         [9 6 8 9 7 5 9]       1.0           10.0
108      Martina       Fausto  12089.0   2BEN  [ 8  8  7 10  8  3  7]       1.0            9.0
109          Tea        Piera  12090.0   2BEN         [6 4 9 3 7 4 5]       0.0            8.0
110        Faith      Luciana  12091.0   2BEN  [ 5  8  4  6 10  5  5]       1.0            8.0
111     Carolina       Aramis  12092.0   2CEN  [10  3  8  3  4  4  9]       0.0            9.0
112         Luce         Yasu  12093.0   2CEN         [4 8 7 9 7 3 3]       0.0            9.0
113        Kamar         Owen  12094.0   2CEN  [ 8  3  3  3 10  4  5]       0.0           10.0
114      Titania        Livia  12095.0   2CEN  [ 5 10  5  7  4  7 10]       1.0            7.0
115    Consolata     Battista  12096.0   2CEN  [10  9  4  6  6  3  8]       1.0            9.0
116      Umberto      Doriana  12097.0   2CEN  [ 4  6 10  3  5  3  8]       0.0            7.0
117       Shaina       Giotto  12098.0   2DEN         [7 7 5 3 8 7 8]       1.0            9.0
118         Dela        Irvin  12099.0   2DEN         [7 6 6 5 3 6 4]       0.0           10.0
119      Gennaro       Carina  12100.0   2DEN  [ 4  8 10  9  9 10  6]       1.0            9.0
120      Marilyn        Norma  12101.0   2DEN         [5 8 5 6 9 7 4]       1.0           10.0
121       Arturo      Novella  12102.0   2DEN         [8 6 4 8 9 8 6]       1.0            8.0
122     Leonardo  Quintiliano  12103.0   2DEN         [8 3 4 9 5 3 4]       0.0            8.0
123       Egidio        Ninfa  12104.0   2EEN  [ 7  6  6 10  7 10  3]       1.0            7.0
124     Fiorenza     Fernanda  12105.0   2EEN  [10  6  3 10  3  6  5]       1.0            7.0
125  Quintiliano        Edera  12106.0   2EEN  [ 5  3  5  9 10  6 10]       1.0            8.0
126        Primo       Aurora  12107.0   2EEN  [ 9  6  7  5  8  5 10]       1.0            9.0
127         Milo     Vittorio  12108.0   2EEN         [9 8 4 6 3 3 7]       0.0           10.0
128         Vega       Ilaria  12109.0   2FIN  [ 6  5  5  5 10  5  8]       1.0            8.0
129        Bruno     Rossella  12110.0   2FIN  [ 3  7  7  8 10  5  9]       1.0           10.0
130        Paola        Scott  12111.0   2FIN         [3 5 7 7 9 5 7]       1.0           10.0
131         Enza         Vito  12112.0   2FIN  [ 9  7 10  9  8  8  6]       1.0           10.0
132        Delia        Carla  12113.0   2FIN         [6 3 6 4 4 4 6]       0.0            9.0
133       Malcom        Dylan  12114.0   2FIN  [ 8  7 10  4  8  6  9]       1.0            7.0
134     Fernando       Albano  12115.0   2GIN         [7 4 5 9 6 3 7]       0.0           10.0
135        Flora       Gunnar  12116.0   2GIN         [4 5 8 6 3 8 3]       0.0            9.0
136    Edelweiss        Sivio  12117.0   2GIN         [5 3 3 5 7 3 7]       0.0            7.0
137       Wilson      Erminio  12118.0   2GIN         [9 7 3 8 4 6 9]       1.0           10.0
138      Cameron      Solange  12119.0   2GIN  [ 8 10  6  8  5  9  9]       1.0           10.0
139       Graham        Agave  12120.0   2GIN         [5 6 3 4 9 5 5]       0.0           10.0
140       Romano     Guerrino  12121.0   2GIN         [8 5 3 9 4 5 9]       1.0            7.0
141     Sigfrido      Roberto  12122.0   2GIN         [5 7 8 5 8 6 8]       1.0            7.0
142      Cristal     Maurizia  12123.0   2GIN         [7 6 9 8 8 8 6]       1.0            8.0
143      Mandisa        Frine  12124.0   2GIN         [5 6 4 4 3 8 4]       0.0            7.0
144    Cristiano    Balthazar  12125.0   2HIN         [5 3 7 8 6 4 8]       0.0           10.0
145     Oliviero      Luciano  12126.0   2HIN  [ 8 10  6  6 10 10  5]       1.0            8.0
146        Marco         Afra  12127.0   2HIN  [ 3  7  9  3  3  7 10]       1.0            7.0
147       Annika    Selvaggia  12128.0   2HIN  [ 3 10  5  8  6  8 10]       1.0            7.0
148        Beryl       Sharar  12129.0   2HIN         [6 6 6 4 9 7 6]       1.0           10.0
149       Marlon       Chiara  12130.0   2HIN         [5 8 4 3 5 6 7]       0.0            8.0
150         Nara       Angelo  12131.0   2HIN         [8 4 9 3 3 6 9]       1.0            8.0
151      Tiffany        Ermes  12132.0   2IEN  [ 3 10  3  9  6  4  7]       1.0            9.0
152       Verena    Francesca  12133.0   2IEN         [3 6 6 6 5 4 9]       0.0            7.0
153      Verilla        Melba  12134.0   2IEN  [ 4  3 10  5  3  9  9]       1.0            7.0
154        Livio         Ulla  12135.0   2IEN         [4 5 4 9 7 6 6]       0.0            8.0
155       Tamara       Duilio  12136.0   2IEN  [ 6 10  3  3  7  7  7]       1.0            9.0
156     Ladislao     Maurizia  12137.0   2IEN         [5 6 8 5 3 9 8]       1.0            9.0
157       Lothar        Megan  12138.0   2IEN         [6 3 4 4 3 4 3]       0.0            7.0
158   Bartolomeo         Siro  12139.0   2IEN  [ 7  6  8  7  8  8 10]       1.0           10.0
159    Selvaggia     Marcella  12140.0   2IEN  [ 9  7  3  8  4 10  8]       1.0            8.0
160        Paolo        Malik  12141.0   2IEN         [7 9 9 6 9 3 5]       1.0            8.0
161    Valentina       Quincy  12142.0   3AEN         [5 4 3 7 3 3 8]       0.0            8.0
162      Mainard      Cecilia  12143.0   3AEN  [ 7  8 10  5  8  7  6]       1.0            9.0
163        Diego      Romilda  12144.0   3AEN  [ 7  5  6 10  8  7 10]       1.0            9.0
164         Enea       Sakura  12145.0   3AEN  [ 9  4  6  3  8 10  3]       1.0            8.0
165      Tiziana          Sem  12146.0   3AEN  [10  6  5  5  8  4  5]       1.0            7.0
166        Tyron      Medardo  12147.0   3AEN  [ 5  5  7  3 10 10  5]       1.0            7.0
167      Fabiana       Azalea  12148.0   3AEN  [ 5 10  8  3  3 10  6]       1.0           10.0
168      Werther       Stella  12149.0   3BEN         [4 6 3 3 6 4 3]       0.0            8.0
169     Angelica     Isabella  12150.0   3BEN         [3 3 6 6 5 9 8]       0.0            9.0
170        Gemma        Fiore  12151.0   3BEN         [9 7 4 8 8 7 5]       1.0            9.0
171      Werther    Baldovino  12152.0   3BEN         [4 8 9 5 8 8 4]       1.0            7.0
172      Paralda        Elvis  12153.0   3BEN         [7 7 8 6 3 6 3]       0.0           10.0
173      Aleramo     Federico  12154.0   3BEN         [7 5 3 8 6 4 7]       0.0            8.0
174      Melinda       Mattia  12155.0   3BEN  [ 7  7  8  3  5 10  4]       1.0           10.0
175        Ivano        Danae  12156.0   3BEN         [9 8 8 9 7 4 4]       1.0            8.0
176         Ilva      Sigmund  12157.0   3BEN         [5 9 6 6 5 3 6]       0.0            9.0
177      Olimpia        Melba  12158.0   3BEN  [ 5  8  3  9  7 10  6]       1.0            9.0
178       Moreno        Nella  12159.0   3CIN         [9 7 8 4 3 9 9]       1.0           10.0
179         Neda       Romano  12160.0   3CIN  [ 6  5 10  5  3 10  5]       1.0           10.0
180      Viviana      Susanna  12161.0   3CIN  [ 5 10  8  6 10 10  9]       1.0            9.0
181      Porthos        Dagon  12162.0   3CIN         [5 3 9 5 8 8 6]       1.0           10.0
182     Fabrizio         Olaf  12163.0   3CIN  [ 9  8  8  5  6  5 10]       1.0           10.0
183      Adriele     Diamante  12164.0   3CIN         [5 8 3 6 5 4 8]       0.0            9.0
184     Norberto      Camelia  12165.0   3DEN  [ 7  4  9  5  5 10  7]       1.0           10.0
185        Sadir       Sheila  12166.0   3DEN  [ 7 10 10  3  5  6  9]       1.0            7.0
186        Zelia         Yasu  12167.0   3DEN  [10  3 10  3  8  9  8]       1.0            8.0
187      Mainard      Umberto  12168.0   3DEN  [ 5  3 10  7  7  3  5]       0.0            8.0
188       Eletta         Dora  12169.0   3DEN  [ 7 10  6  5 10  8  9]       1.0            9.0
189         Igea     Bernardo  12170.0   3DEN         [6 6 9 7 5 3 9]       1.0            8.0
190    Ferruccio      Rachele  12171.0   3DEN         [9 9 8 6 8 5 3]       1.0           10.0
191         Tara     Wolfgang  12172.0   3EIN         [8 4 8 6 6 4 4]       0.0           10.0
192      Alberta     Federica  12173.0   3EIN         [4 6 7 5 3 9 9]       1.0            7.0
193       Savino         Clio  12174.0   3EIN         [6 5 8 7 8 6 7]       1.0            8.0
194      Giacomo    Stanislao  12175.0   3EIN         [7 7 3 9 4 8 6]       1.0            8.0
195        Jader       Lorena  12176.0   3EIN         [5 7 4 4 5 7 5]       0.0            9.0
196       Franco     Angelica  12177.0   3FIN  [ 5  3  5  6  4  6 10]       0.0            9.0
197        Elvio      Tiziano  12178.0   3FIN  [ 9  8  4  6 10 10  7]       1.0            7.0
198     Vittoria         Yuri  12179.0   3FIN         [3 3 3 5 7 8 6]       0.0           10.0
199        Luana      Alessia  12180.0   3FIN  [ 5  3  3  4 10 10  6]       0.0            7.0
200       Armida       Chiara  12181.0   3FIN  [ 6  9  6  5  4  4 10]       1.0            8.0
201        Alida        Altea  12182.0   3FIN  [ 8  4  4 10  3  9  8]       1.0            7.0
202         Rolf      Roswita  12183.0   3FIN  [ 8  8  8  3  7  5 10]       1.0            9.0
203        Paolo      Aleramo  12184.0   3FIN  [ 6 10  7  5  5  7  8]       1.0            8.0
204       Aretha       Vissia  12185.0   3FIN         [8 6 3 8 7 6 5]       1.0            7.0
205        Irene        Ester  12186.0   3FIN  [ 9 10  6  3  8  6  5]       1.0           10.0
206    Lanfranco       Sennen  12187.0   4AEN  [ 5  4  6  4  4  9 10]       1.0            7.0
207      Lavinia      Daniela  12188.0   4AEN         [4 4 4 9 6 5 5]       0.0            9.0
208         Cora         Leon  12189.0   4AEN  [10  4  9 10  3  8 10]       1.0            9.0

## Indexing

In [5]:
## Guardo tutte le colonne
studenti.columns
## Guardo la colonna nomi
studenti["Nome"]
## Un altro modo per guardare una colonna
studenti.Nome
## Guardare nome e cognomi
studenti[["Nome", "Cognome"]]

            Nome      Cognome
0           Inga       Adolfo
1           Leon        Bardo
2           Orso   Elisabetta
3          Megan   Guendalina
4            Pio      Eugenio
5       Raimonda     Giuliana
6         Tullia         Fara
7         Silvia     Gardenia
8        Simeone      Assunta
9           Nara     Graziano
10           Ada      Doriana
11         Maria       Lilith
12         Alida        Altea
13       Jessica      Ignazio
14       Leonida        Aime√®
15       Ignazio        Ermes
16           Tia       Egidio
17      Lancelot      Edgardo
18       Satinka        Bruna
19        Altair         Jael
20     Anastasia          Ebe
21        Cedric        Bjorn
22        Cesara         Vida
23       Leonida      Madonna
24           Era     Filomena
25          Ford       Rowena
26        Enrica      Letizia
27          Dina        Medea
28        Evania       Melvin
29       Malvina      Marilyn
30       Gustavo      Elettra
31        Silvia        Maude
32        Urania      Primula
33      Fiorella       Rohana
34      Manfredo         Ciro
35       Romilda    Salvatore
36         Melia    Polissena
37       Celesta      Mildred
38        Mirina        Xenia
39          Edda       Xantha
40          Elia     Emiliana
41         Zelia       Annika
42         Lidia     Vincenzo
43     Genoveffa    Aquilante
44          Ivan      Rosalia
45       Adriana      Attilio
46      Marilena   Costantino
47       Velania         Egle
48          Ymir         Igea
49      Euridice         Ford
50         Fabio      Zuleika
51         Milva      Ornella
52        Duilio     Galeazzo
53          Otto       Oreste
54        Leslie         Edda
55         Talia    Anastasia
56       Anselmo        Folco
57        Rowena         Aura
58     Edelweiss          Ugo
59      Ortensia       Romolo
60      Mercedes      Melania
61         Liala         Luna
62       Ancilla   Costantino
63       Cecilia      Camillo
64         Olisa          Eco
65      Beatrice       Bianca
66         Mario      Natalia
67       Rachele      Camelia
68        Werner   Margherita
69       Paralda         Wala
70      Ludovico      Tiffany
71         Kamar       Moanna
72        Onella      Santino
73      Floriano         Egle
74       Alberto        Izusa
75       Vittore   Sebastiano
76       Vassjli      Morgana
77       Dolcina     Perceval
78          Lora     Fiorenzo
79      Adelaide     Samantha
80      Marilena      Candida
81         Mario       Romolo
82           Sem        Drago
83        Thelma       Andrea
84        Alhena      Mafalda
85          Orio         Enki
86       Giacomo      Celeste
87    Guicciardo     Ambrogio
88       Bibiana      Barbara
89          Vito        Uriel
90       Ignazio         Alan
91        Donato     Ludmilla
92       Melania      Alfredo
93        Donata         Elfo
94    Sebastiano        Ivana
95         Athos      Zuleika
96           Nem       Moanna
97        Kendra    Ferruccio
98           Lia       Carina
99       Alfonso        Frida
100      Massimo        Jader
101     Domenica      Valeria
102      Verilla        Delia
103      Delfino      Gaspare
104        Edith        Alida
105     Giuliana     Fiorenza
106         Dino         Emma
107      Adriele        Nadia
108      Martina       Fausto
109          Tea        Piera
110        Faith      Luciana
111     Carolina       Aramis
112         Luce         Yasu
113        Kamar         Owen
114      Titania        Livia
115    Consolata     Battista
116      Umberto      Doriana
117       Shaina       Giotto
118         Dela        Irvin
119      Gennaro       Carina
120      Marilyn        Norma
121       Arturo      Novella
122     Leonardo  Quintiliano
123       Egidio        Ninfa
124     Fiorenza     Fernanda
125  Quintiliano        Edera
126        Primo       Aurora
127         Milo     Vittorio
128         Vega       Ilaria
129        Bruno     Rossella
130        Paola        Scott
131         Enza         Vito
132        Delia        Carla
133       Malcom        Dylan
134     Fernando       Albano
135        Flora       Gunnar
136    Edelweiss        Sivio
137       Wilson      Erminio
138      Cameron      Solange
139       Graham        Agave
140       Romano     Guerrino
141     Sigfrido      Roberto
142      Cristal     Maurizia
143      Mandisa        Frine
144    Cristiano    Balthazar
145     Oliviero      Luciano
146        Marco         Afra
147       Annika    Selvaggia
148        Beryl       Sharar
149       Marlon       Chiara
150         Nara       Angelo
151      Tiffany        Ermes
152       Verena    Francesca
153      Verilla        Melba
154        Livio         Ulla
155       Tamara       Duilio
156     Ladislao     Maurizia
157       Lothar        Megan
158   Bartolomeo         Siro
159    Selvaggia     Marcella
160        Paolo        Malik
161    Valentina       Quincy
162      Mainard      Cecilia
163        Diego      Romilda
164         Enea       Sakura
165      Tiziana          Sem
166        Tyron      Medardo
167      Fabiana       Azalea
168      Werther       Stella
169     Angelica     Isabella
170        Gemma        Fiore
171      Werther    Baldovino
172      Paralda        Elvis
173      Aleramo     Federico
174      Melinda       Mattia
175        Ivano        Danae
176         Ilva      Sigmund
177      Olimpia        Melba
178       Moreno        Nella
179         Neda       Romano
180      Viviana      Susanna
181      Porthos        Dagon
182     Fabrizio         Olaf
183      Adriele     Diamante
184     Norberto      Camelia
185        Sadir       Sheila
186        Zelia         Yasu
187      Mainard      Umberto
188       Eletta         Dora
189         Igea     Bernardo
190    Ferruccio      Rachele
191         Tara     Wolfgang
192      Alberta     Federica
193       Savino         Clio
194      Giacomo    Stanislao
195        Jader       Lorena
196       Franco     Angelica
197        Elvio      Tiziano
198     Vittoria         Yuri
199        Luana      Alessia
200       Armida       Chiara
201        Alida        Altea
202         Rolf      Roswita
203        Paolo      Aleramo
204       Aretha       Vissia
205        Irene        Ester
206    Lanfranco       Sennen
207      Lavinia      Daniela
208         Cora         Leon
209        Waldo       Agnese
210       Gareth      Melania
211       Salom√®        Zaira
212     Cornelia   Margherita
213         Tara     Griselda
214       Sheila        Amina
215        Tessa      Alfredo
216      Attilio        Carlo
217        Uriel     Giuditta
218       Paloma       Oriana
219     Patrizia        Mizar
220        Rocco        Irene
221   Guendalina        Shada
222          Tea      Gisella
223      Petunia     Giovanni
224      Celeste       Wilson
225     Virginia     Jonathan
226     Meredith      Loreley
227       Enrica         Joel
228       Matteo        Ghino
229     Cordelia     Lamberto
230        Guido      Videmar
231     Vincenzo        Alfio
232      Rodolfo     Aristide
233        Tyler    Gelsomina
234          Era      Alessia
235      Gaetano       Nuriel
236        Mirra      Umberta
237      Azzurra         Kirk
238          Jin          Sem
239     Graziano      Carmelo
240       Shaula       Verena
241        Jamil      Camilla
242      Filippo       Idalia

In [6]:
## Prendo un dataframe usando l'index
studenti.iloc[0]
studenti.iloc[0,0]
studenti.iloc[[0,1], [0,1,2]]

   Nome Cognome   Codice
0  Inga  Adolfo  11981.0
1  Leon   Bardo  11982.0

In [7]:
## Utilizzo senza usare l'index
studenti.loc[0, "Nome"]
studenti.loc[[0,1], ["Nome", "Cognome"]]
studenti.loc[0:2, "Nome" : "Codice"]

   Nome     Cognome   Codice
0  Inga      Adolfo  11981.0
1  Leon       Bardo  11982.0
2  Orso  Elisabetta  11983.0

In [8]:
## Modifico Codice
## Rinomino assegnando
# studenti.columns = ["Nome", "Cognome", "Matricola", "Classe", "Voti", "Promosso"]
## Rinomino usando rename
studenti.rename(columns={"Codice" : "Matricola"}, inplace = True)
## Rendo tutto minuscolo
studenti.columns = [x.lower() for x in studenti.columns]
# studenti

In [9]:
## Setto il codice come index
# studenti = studenti.set_index("Codice", inplace = True)
studenti.set_index("matricola", inplace = True)
studenti.loc[11981]

nome                        Inga
cognome                   Adolfo
classe                      1AIN
voti             [3 8 6 9 3 7 7]
promosso                       1
comportamento                  8
Name: 11981.0, dtype: object

## Divisione promossi e bocciati

In [10]:
## Prendo tutti i bocciati
filt = (studenti["promosso"] == 0)

In [11]:
## Prendo la classe e i voti dei promossi
studenti.loc[~filt, ["classe", "voti"]]
## Conto il numero di bocciati
studenti["promosso"].value_counts()[0]

70

## Altri dati

In [12]:
# studenti_nuovi
## Elimino la prima riga
# studenti_nuovi.drop(0)
## Modifico la seconda riga usando loc
# studenti_nuovi.loc[1] = ["Angelica", "Rossi", 12300, "1IEN"]
## Modifico un valore della seconda riga usando at
# studenti_nuovi.at[2, "Classe"] = "1IEN"
## Modifico un valore usando iat
# studenti_nuovi.iat[0, 0] = "Marco"